name: igreja_app
description: "Aplicativo para igrejas."
publish_to: 'Tiago Oliveira'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  
  share_plus: ^7.0.0
  http: ^0.13.6
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  font_awesome_flutter: ^10.2.1
  url_launcher: ^6.0.20
  maps_launcher: ^2.0.0

  flutter_launcher_icons: ^0.13.1

  flutter_localizations:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/ic_launcher.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/load_img.png
    - assets/images/qrcode.png
    - assets/json/bibliaAveMaria.json
    - assets/json/oracoes.json
